<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-KBNET8L" failures="1" tests="3" name="Login" time="0.055" errors="0" timestamp="2022-10-24T13:14:47 IST">
  <testcase classname="com.retry.TestLogin" name="doLogin" time="0.008"/>
  <testcase classname="com.retry.TestLogin" name="registerUsers" time="0.003">
    <skipped/>
  </testcase> <!-- registerUsers -->
  <testcase classname="com.retry.TestLogin" name="registerUsers" time="0.001">
    <failure type="java.lang.AssertionError" message="Failing the test as the condition is not met">
      <![CDATA[java.lang.AssertionError: Failing the test as the condition is not met
at com.retry.TestLogin.registerUsers(TestLogin.java:19)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 28 stack frames]]>
    </failure>
  </testcase> <!-- registerUsers -->
</testsuite> <!-- Login -->
